field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  e65bd1e5-abf6-43e6-a3f0-2fbb329e35c4:
    tabs:
      -
        elements:
          -
            fieldUid: 24bd1247-7ed2-48e8-af76-5b8ffc486ef6 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1723daa2-1605-463e-bb38-4472e9bcfaf4
            warning: null
            width: 100
          -
            fieldUid: 8c274864-9cf0-4ef9-b4bd-88da544515ad # Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521a42a3-5a35-43b3-9c62-129f039d3229
            warning: null
            width: 100
          -
            fieldUid: 6ee9b9a7-d12d-4c9b-b069-586609cb5ea9 # Link Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b81b8ef-34cb-4cb8-9355-666bc5398c21
            warning: null
            width: 100
          -
            fieldUid: 3b1b9f85-3554-4b4a-8d39-467bf5e4a35d # Internal Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79e1cd1c-b273-4ae7-91d1-ca890d25eaf6
            warning: null
            width: 100
          -
            fieldUid: 55c6cb51-defc-4e30-bc18-e524de65b7b7 # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82dcbab5-40bc-4e35-b60c-5c82732a9e90
            warning: null
            width: 100
          -
            fieldUid: 42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8 # Link Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37e5a668-9ae1-4caf-b8d9-a2335cab28eb
            warning: null
            width: 100
          -
            fieldUid: 0ba28a66-d3aa-4c97-ad77-8e26087b3d70 # Narrow Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 892da9c7-a6ed-4d7c-9e8c-3073f53d5fe2
            warning: null
            width: 100
        name: Content
        uid: 8e6c3502-8203-4d4f-a932-fa343b17b998
fields:
  0ba28a66-d3aa-4c97-ad77-8e26087b3d70: # Narrow Width
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: narrowWidth
    instructions: null
    name: 'Narrow Width'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  3b1b9f85-3554-4b4a-8d39-467bf5e4a35d: # Internal Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: internalLink
    instructions: null
    name: 'Internal Link'
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6ee9b9a7-d12d-4c9b-b069-586609cb5ea9: # Link Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkLabel
    instructions: null
    name: 'Link Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c274864-9cf0-4ef9-b4bd-88da544515ad: # Information
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: information
    instructions: 'Allows HTML & Twig syntax.'
    name: Information
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  24bd1247-7ed2-48e8-af76-5b8ffc486ef6: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Allows HTML & Twig syntax.'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8: # Link Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkIcon
    instructions: null
    name: 'Link Icon'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Arrow - Left'
            -
              - value
              - arrowLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Arrow - Right'
            -
              - value
              - arrowRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Arrow - Up'
            -
              - value
              - arrowUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Arrow - Down'
            -
              - value
              - arrowDown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Brochure
            -
              - value
              - brochure
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Map Pin'
            -
              - value
              - mapPin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - News
            -
              - value
              - news
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  55c6cb51-defc-4e30-bc18-e524de65b7b7: # External Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: null
    name: 'External Link'
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: ctaCaption
name: 'CTA Caption'
sortOrder: 6
