field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  2e620162-c9b6-427b-8b34-01749ceed604:
    tabs:
      -
        elements:
          -
            fieldUid: e44383bb-8f5a-4b3b-9114-30a955feb64c # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1da2001e-b1d4-4216-ba64-afa70351c1a2
            warning: null
            width: 100
          -
            fieldUid: a4c579fb-e9c9-4d0c-91f6-1b3d9980c5ee # Success Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec58db74-50a6-4093-8292-d0c5ab60f6ef
            warning: null
            width: 100
        name: Content
        uid: 0c40cfb4-32d4-4f05-8813-99b00af4d589
fields:
  a4c579fb-e9c9-4d0c-91f6-1b3d9980c5ee: # Success Message
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: successMessage
    instructions: 'Optional success message for this specific form.'
    name: 'Success Message'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e44383bb-8f5a-4b3b-9114-30a955feb64c: # Form
    columnSuffix: null
    contentColumnType: integer
    fieldGroup: null
    handle: form
    instructions: null
    name: Form
    searchable: true
    translationKeyFormat: null
    translationMethod: none
    type: Solspace\Freeform\FieldTypes\FormFieldType
handle: form
name: Form
sortOrder: 8
