field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  74ad9d74-87f7-47ce-979e-cd93cc0f6002:
    tabs:
      -
        elements:
          -
            fieldUid: 2d7b7e2f-71b1-4b25-8501-c8edc07a7f18 # Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2d7b7e2f-71b1-4b25-8501-c8edc07a7f18: # Embed Code
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: embedCode
    instructions: 'Go to Google Maps, find a location, click the "Share" button, click "Embed a map", click "Copy HTML", then paste into the text box below.'
    name: 'Embed Code'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: googleMapEmbed
name: 'Google Map Embed'
sortOrder: 10
