field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  43071b8b-6243-4eea-b70b-e6122dd5a909:
    tabs:
      -
        elements:
          -
            fieldUid: b28c567f-a9f9-4d96-848b-1de28c643417 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db91b6bf-05af-4356-b713-a66592a119bd
            warning: null
            width: 100
        name: Content
        uid: f6fd8c78-a3eb-4219-8c73-55c6c89c190c
fields:
  b28c567f-a9f9-4d96-848b-1de28c643417: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
