field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  6f1b2935-dba4-460d-be70-b29a7aa0aa60:
    tabs:
      -
        elements:
          -
            fieldUid: dad3b3bd-ab3c-486d-a552-b3cc718f8e1c # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 016d6fd9-8677-47f0-8771-a220936b734b
            warning: null
            width: 100
          -
            fieldUid: a65ec270-2111-40c2-bf47-f3d6d929603a # Pre Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 056f209b-7979-4291-8553-6faa4b0e49a1
            warning: null
            width: 100
          -
            fieldUid: f109ee5b-bb41-47ce-aaa0-53b5304e0e22 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11fe54a4-5984-413c-95c8-900925b8a814
            warning: null
            width: 100
          -
            fieldUid: 3b943244-76d1-4973-9d71-6ec6c109e255 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 123f3984-590d-41e3-a874-2c477b21c0e0
            warning: null
            width: 100
          -
            fieldUid: 3ad065f3-cd49-4ea6-91e3-12d3a0f0e30f # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86f23cc1-2e98-47e1-9a05-ba947ade11f1
            warning: null
            width: 100
          -
            fieldUid: 913eb47c-ce43-4325-bb3a-1f5d99065038 # Highlight Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c92a655-fcc1-4f32-abb6-86ef8213a8d1
            warning: null
            width: 100
        name: Content
        uid: c7e1b071-3935-47c7-9acf-9c6f3d7f595e
fields:
  3ad065f3-cd49-4ea6-91e3-12d3a0f0e30f: # Text Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text Color'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Black Text'
            -
              - value
              - blackText
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'White Text'
            -
              - value
              - whiteText
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  3b943244-76d1-4973-9d71-6ec6c109e255: # Sub Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: null
    name: 'Sub Heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  913eb47c-ce43-4325-bb3a-1f5d99065038: # Highlight Text
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: highlightText
    instructions: 'Will apply a background for the text to increase contrast from the background.'
    name: 'Highlight Text'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a65ec270-2111-40c2-bf47-f3d6d929603a: # Pre Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: preHeading
    instructions: null
    name: 'Pre Heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dad3b3bd-ab3c-486d-a552-b3cc718f8e1c: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a36fa6aa-4824-448f-82cf-b3086f8582c5' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f109ee5b-bb41-47ce-aaa0-53b5304e0e22: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageAndHeadings
name: 'Image and Headings'
sortOrder: 2
