field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  b7542268-90e7-488e-aaf2-8c6695a2948c:
    tabs:
      -
        elements:
          -
            fieldUid: aa1aa6b7-0e81-4b68-8694-ed5f543f38bc # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88b22500-1a2a-4744-be8c-2e6020bb4cdf
            warning: null
            width: 100
          -
            fieldUid: eb910859-8baf-408a-ae9a-3af97b637806 # Top Border
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 691cb210-126a-4a63-a5bb-ebe3e414160d
            warning: null
            width: 100
          -
            fieldUid: cdc345f6-dec9-46b7-80b5-6de7918fcdf3 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f463e9b-a0ae-4024-bb4d-e5427ca3a1e8
            warning: null
            width: 100
          -
            fieldUid: fadcfcb9-b6bc-4adf-9adb-18ba2e89bfb7 # Narrow Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a23485b0-fc56-44e9-870e-51520b2e3073
            warning: null
            width: 100
        name: Content
        uid: a3ac54c2-d758-450a-9127-4ae990c8f440
fields:
  aa1aa6b7-0e81-4b68-8694-ed5f543f38bc: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: VHC.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cdc345f6-dec9-46b7-80b5-6de7918fcdf3: # Layout
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Image Left'
            -
              - value
              - imageLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Image Full Width'
            -
              - value
              - imageFullWidth
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Image Right'
            -
              - value
              - imageRight
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  eb910859-8baf-408a-ae9a-3af97b637806: # Top Border
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: topBorder
    instructions: null
    name: 'Top Border'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  fadcfcb9-b6bc-4adf-9adb-18ba2e89bfb7: # Narrow Width
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: narrowWidth
    instructions: null
    name: 'Narrow Width'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: richText
name: 'Rich Text'
sortOrder: 5
