fieldLayouts:
  d1f76894-056f-4ceb-be30-e908b48b3951:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c00248a9-4745-4d1e-b50b-4702cf7bfd7f
            warning: null
            width: 100
          -
            fieldUid: 27881ad3-1379-497a-91a6-d495b2bbc7d1 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3455a89c-de3b-4052-8a29-f99fd0ffdc8d
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6fde41e-6343-4fef-838a-385bf08a9ab9
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba04c7ea-c64b-4b0c-bc28-414269aba883
            warning: null
            width: 100
        name: Content
        uid: f8d7e165-31bc-4557-acf8-c06cfdb6cded
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5dc0e35e-7c51-403c-bd23-c6945d019ad3
            warning: null
            width: 100
        name: SEO
        uid: 6a198f44-c19d-42dc-9e3c-9514f4414132
handle: about
hasTitleField: false
name: About
section: 977f4737-eaaa-4d0f-aadb-10251ee1c4ff # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
