fieldLayouts:
  435a9c09-fba5-4a0f-99d7-137fe73929f1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b01059e1-816b-4696-8e15-b57cdf4b0dd1
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c414ee55-92ae-4acc-b8ad-797c0b2a6604
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abdc96c1-ea73-4c21-960a-65ecaf7b777e
            warning: null
            width: 100
        name: Content
        uid: 94ecea37-512d-409f-a950-f72033a22017
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9a11945-755b-446d-a2ab-867d0549717a
            warning: null
            width: 100
        name: SEO
        uid: a91f7c36-101f-4b31-ab06-6bcbb7fae112
handle: contact
hasTitleField: false
name: Contact
section: 8f6c3046-e9ee-4df9-af84-6dc0199f01da # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
