fieldLayouts:
  268b8d62-05d6-417a-9a6b-ed707ea8dd4b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8b78b8de-8c42-4fb9-93e2-aac6c4b6fa48
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c4431d-c47e-4f71-be6f-822a361ea08f
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8f20da1-e003-4558-b94c-6fbb7d93e290
            warning: null
            width: 100
        name: Content
        uid: 5bb95504-52d1-421b-96ad-250b124e139a
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d261b3b2-bb97-447e-9647-a7e5f6cbcba1
            warning: null
            width: 100
        name: SEO
        uid: 101d8795-8da3-4a62-ae6b-0217fac54d72
handle: exhibit
hasTitleField: true
name: Exhibit
section: c49dac11-102e-429e-8bcc-5c8d99508dcb # Exhibits
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
