fieldLayouts:
  e1fad73a-2e23-4fa8-8f33-5037fe6b6d76:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1fd34966-3f04-4530-9990-611cfa0a6146
            warning: null
            width: 100
          -
            fieldUid: cf7038b3-3aa7-4d1f-8a12-1cf0017d5b2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56b8cad3-9e11-4ed2-97df-9d4f36987e99
            warning: null
            width: 100
          -
            fieldUid: c3286b59-368a-4fdf-8dbe-48084247c9e2 # Featured Exhibits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 466f81a5-985f-49bd-9b5d-dddb9b387404
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21356ca6-832a-4ae2-b3d2-408e1b3b48c6
            warning: null
            width: 100
        name: Content
        uid: dac52723-1ad1-4b0d-b305-9d19f173d0fe
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca8cf6d9-94bf-485d-83a2-bf7e7643a506
            warning: null
            width: 100
        name: SEO
        uid: f97dcab3-7e40-44ac-ab40-127a80609f54
handle: home
hasTitleField: false
name: Home
section: 9d1ed50c-2239-4171-8b5a-ab121973301f # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
