fieldLayouts:
  624b2b8f-343a-4481-a172-20fe3cc8947d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4a1e158-f42b-4247-acdb-a221faef6fbe
            warning: null
            width: 100
          -
            fieldUid: a73bf239-f2f0-45ac-b84d-361e5dd1a75f # Pagination Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95627671-b31d-44a2-a044-100da9afaae7
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823dbb33-983a-4cd0-ac3d-c6c85234743f
            warning: null
            width: 100
        name: Content
        uid: 53687072-e58e-4b81-87ca-46dae2f02675
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0b210a8-9fdc-4286-9c97-e5dc9a35dd03
            warning: null
            width: 100
        name: SEO
        uid: 99c94680-2a52-4526-89f1-bed83bab2619
handle: news
hasTitleField: false
name: News
section: 9b80c4d3-7a27-4bc4-af25-742e6cf5f77a # News
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
