fieldLayouts:
  10b19456-af43-4ddc-95ec-daf105ffcc38:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c6e43acd-fe82-4bae-bc8f-4a010eb52084
            warning: null
            width: 100
        name: Content
        uid: a32535ef-ef8d-4801-980f-19499eb7b6f4
handle: styleguide
hasTitleField: false
name: Styleguide
section: 0edb3240-3f53-4f13-a789-2bd0b6cae755 # Styleguide
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
