fieldLayouts:
  c266fd55-9906-470d-b73b-a1e12e86bb69:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be83b77a-099a-4214-8c92-01a2a4451823
            warning: null
            width: 100
          -
            fieldUid: beb1c87a-67bb-421f-933f-4bc3d1e125e3 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11707c41-c00c-4dc5-bb79-f1f531a5d627
            warning: null
            width: 100
          -
            fieldUid: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d15cae13-1a55-4e27-85e4-1b7d4187892c
            warning: null
            width: 100
        name: Content
        uid: f70e57da-e2b6-4b27-a16c-f164b129df6b
      -
        elements:
          -
            fieldUid: c8da1bd9-67c9-402f-8a95-aeaec337e207 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df0bbfdb-068a-41c5-9d68-538ca8c89e4b
            warning: null
            width: 100
        name: SEO
        uid: c7e2b4e0-3126-4862-b821-869071a0fc9e
handle: visit
hasTitleField: false
name: Visit
section: 8a02b167-35d9-4c71-bc4b-59ee401246e3 # Visit
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
