field: 778abb42-18bd-447c-99ae-483c775ed3bd # Content Blocks
fieldLayouts:
  a0493dba-06c8-4dd6-ba71-c90579ce7c72:
    tabs:
      -
        elements:
          -
            fieldUid: c88dc31c-dfde-42c6-93df-6af9d0c907b8 # URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c88dc31c-dfde-42c6-93df-6af9d0c907b8: # URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: embed
    instructions: 'Enter a URL link to Twitter tweet, Instagram post, YouTube video, and more.'
    name: URL
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
handle: embed
name: 'Social Embed'
sortOrder: 9
