columnSuffix: null
contentColumnType: text
fieldGroup: 71a8e9e8-3d7d-4ceb-91f8-482de5453eab # Home
handle: heading
instructions: ''
name: Heading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
