columnSuffix: null
contentColumnType: text
fieldGroup: 1bff9c9f-5c93-4679-967d-0f9095c856fa # Common
handle: seo
instructions: null
name: SEO
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogType
    - ogTitle
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
    - seoImageDescription
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterCreator
    - twitterTitle
    - twitterDescription
    - twitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
