columnSuffix: null
contentColumnType: text
fieldGroup: c0ba2861-5497-46d7-86b4-71dcb76f2a16 # News Articles
handle: summary
instructions: 'Short summary for News page and RSS feed.'
name: Summary
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
