dateModified: 1684282609
email:
  fromEmail: support@craftcms.com
  fromName: 'Europa Museum'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ''
    host: $SMTP_HOST
    password: ''
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: ''
    username: ''
  transportType: craft\mail\transportadapters\Smtp
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: ''
      cfPrefix: ''
      expires: ''
      keyId: ''
      makeUploadsPublic: true
      region: $AWS_REGION
      secret: ''
      storageClass: ''
      subfolder: assets/volumes/images
    type: craft\awss3\Fs
    url: $S3_BASE_URL
  imagesLocal:
    hasUrls: true
    name: 'Images (local)'
    settings:
      path: '@webroot/assets/volumes/images'
    type: craft\fs\Local
    url: '@web/assets/volumes/images'
  runtime:
    hasUrls: false
    name: Runtime
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: ''
      cfPrefix: ''
      expires: ''
      keyId: ''
      makeUploadsPublic: false
      region: $AWS_REGION
      secret: ''
      storageClass: ''
      subfolder: runtime
    type: craft\awss3\Fs
    url: null
meta:
  __names__:
    0b3ab84a-728c-4dfa-b505-ee524b9631d9: Home # Home
    0ba28a66-d3aa-4c97-ad77-8e26087b3d70: 'Narrow Width' # Narrow Width
    0d3f8f65-dde1-4921-a575-26ade4545fc9: Slider # Slider
    0edb3240-3f53-4f13-a789-2bd0b6cae755: Styleguide # Styleguide
    00f86307-b225-423b-bd34-b70af6632cf2: 'Link Label' # Link Label
    1addbebe-4d59-4c1d-9607-6c47999665df: 'Links - Middle' # Links - Middle
    1bff9c9f-5c93-4679-967d-0f9095c856fa: Common # Common
    2b1996eb-1a60-4257-b4ab-2e41c49fbd06: Image # Image
    2baf1b70-dad1-4c27-b485-a94b23a3e89f: 'Site Administrators' # Site Administrators
    2d7b7e2f-71b1-4b25-8501-c8edc07a7f18: 'Embed Code' # Embed Code
    3ad065f3-cd49-4ea6-91e3-12d3a0f0e30f: 'Text Color' # Text Color
    03ad2302-4a79-4d90-91f8-bb515f0157d0: Styleguide # Styleguide
    3b1b9f85-3554-4b4a-8d39-467bf5e4a35d: 'Internal Link' # Internal Link
    3b943244-76d1-4973-9d71-6ec6c109e255: 'Sub Heading' # Sub Heading
    4c127ec9-df18-4d62-bd02-cf8b5044f7ea: 'Left Stat Label' # Left Stat Label
    4e48185d-8e74-4fa1-b4b4-fdac5ceddf6d: Heading # Heading
    5bd803f3-dec3-41e6-b829-f90b49ac8dd3: About # About
    5ccbb75b-a9e9-455a-baf9-60aaa799d452: 'Right Stat Label' # Right Stat Label
    5f06df0c-02b7-4b2d-9b75-4b22a09c3a12: 'Right Stat Value' # Right Stat Value
    6b0e8c8f-3b9a-440d-b5ad-e209cd4eb486: 'News Category' # News Category
    6c31cab7-7f79-4628-b345-9a700a16a726: Entry # Entry
    6ee9b9a7-d12d-4c9b-b069-586609cb5ea9: 'Link Label' # Link Label
    6fb16db4-9ff1-412f-8cde-bc13843d78e8: 'CTA Caption' # CTA Caption
    7cce3872-9055-454a-8fdc-45cbccec785b: 'Left Stat Value' # Left Stat Value
    8a02b167-35d9-4c71-bc4b-59ee401246e3: Visit # Visit
    8b592bee-c976-4c83-be76-d749cc991410: 'Image Caption' # Image Caption
    8c274864-9cf0-4ef9-b4bd-88da544515ad: Information # Information
    8df6d29d-59a0-44ee-80e5-f69849956547: 'Text Color' # Text Color
    8f6c3046-e9ee-4df9-af84-6dc0199f01da: Contact # Contact
    8f9a20e9-754d-490d-baa6-b9512feafa91: 'Rich Text' # Rich Text
    9b80c4d3-7a27-4bc4-af25-742e6cf5f77a: News # News
    9ba346ec-12cc-4b07-9a30-677efc6e97c1: 'Google Map Embed' # Google Map Embed
    9d1ed50c-2239-4171-8b5a-ab121973301f: Home # Home
    9f8a4de3-d72b-4d23-bb81-c83ef4611889: Exhibitions # Exhibitions
    11b555a2-89cb-434c-a97c-8bf858a76326: 'Slide Images' # Slide Images
    011d792e-37cb-488e-a6e1-1b1800027fe9: 'Demo Tags' # Demo Tags
    13b5cd9c-c5b1-40bb-8a8a-dc14815aabad: Exhibit # Exhibit
    13b529cb-1236-4eb5-95a0-e20c2358385e: 'Slide Entries' # Slide Entries
    19f3873e-d59d-48d0-bbee-1c25acd90c6c: News # News
    20d3ac0c-0016-4714-9ce6-ffd91f1a0d5b: 'Europa Museum' # Europa Museum
    24bd1247-7ed2-48e8-af76-5b8ffc486ef6: Heading # Heading
    24db24b1-bf70-414a-8652-ba22d7b0dfc3: Form # Form
    42ad64e7-b07b-4601-9e6b-2d21bc0fe5d8: 'Link Icon' # Link Icon
    52ff2568-6318-44d5-a130-818c19f83360: 'External Link' # External Link
    55c6cb51-defc-4e30-bc18-e524de65b7b7: 'External Link' # External Link
    59eb8fe2-8081-44bc-82ee-b7bc5f91c4ec: Summary # Summary
    71a8e9e8-3d7d-4ceb-91f8-482de5453eab: Home # Home
    079ddf1a-d985-4de2-9929-8dc87fa2047f: 'News Category' # News Category
    83ef9ed9-6360-4f64-abbb-920baeb2048e: 'Featured Entry' # Featured Entry
    371b985f-f191-4c1b-8785-c4133cbb42fc: Heading # Heading
    599f0646-f724-4ce4-a810-a8eaf7798b2d: 'Links - Right' # Links - Right
    666bcffb-61d7-43b4-a9f5-8c51c458b356: 'News Articles' # News Articles
    701ed750-1c7f-4b39-9be6-2c25746f29ba: 'Image Alt' # Image Alt
    778abb42-18bd-447c-99ae-483c775ed3bd: 'Content Blocks' # Content Blocks
    823ac85e-6b3c-499a-bbdc-99a4e2432138: 'Content Managers' # Content Managers
    913eb47c-ce43-4325-bb3a-1f5d99065038: 'Highlight Text' # Highlight Text
    977f4737-eaaa-4d0f-aadb-10251ee1c4ff: About # About
    27881ad3-1379-497a-91a6-d495b2bbc7d1: 'Hero Title' # Hero Title
    85241ed2-6bbd-4dd0-af5c-07842116ccf3: 'Dark UI' # Dark UI
    a4b1ac77-02b4-4121-91b4-8d3754b290d4: 'Image and Headings' # Image and Headings
    a4c579fb-e9c9-4d0c-91f6-1b3d9980c5ee: 'Success Message' # Success Message
    a36fa6aa-4824-448f-82cf-b3086f8582c5: Images # Images
    a65ec270-2111-40c2-bf47-f3d6d929603a: 'Pre Heading' # Pre Heading
    a73bf239-f2f0-45ac-b84d-361e5dd1a75f: 'Pagination Count' # Pagination Count
    a90cc22d-485c-4cd7-a4b9-63a8a637e90d: Navigation # Navigation
    aa1aa6b7-0e81-4b68-8694-ed5f543f38bc: __blank__ # __blank__
    b28c567f-a9f9-4d96-848b-1de28c643417: __blank__ # __blank__
    b39c0003-6393-4175-8698-6edef920f7fd: Exhibitions # Exhibitions
    b7672c12-833b-4554-afc9-ec3d68dbd78d: 'CTA Link Text' # CTA Link Text
    beb1c87a-67bb-421f-933f-4bc3d1e125e3: 'Hero Image' # Hero Image
    beffd6f6-3f04-4ae0-b2c6-71a4e419ab57: French # French
    c0ba2861-5497-46d7-86b4-71dcb76f2a16: 'News Articles' # News Articles
    c8da1bd9-67c9-402f-8a95-aeaec337e207: SEO # SEO
    c49dac11-102e-429e-8bcc-5c8d99508dcb: Exhibits # Exhibits
    c88dc31c-dfde-42c6-93df-6af9d0c907b8: URL # URL
    c3286b59-368a-4fdf-8dbe-48084247c9e2: 'Featured Exhibits' # Featured Exhibits
    c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: English # English
    ccf2030d-2ade-4d8c-9a90-4f50b2ffd37e: Visit # Visit
    cdc345f6-dec9-46b7-80b5-6de7918fcdf3: Layout # Layout
    cf7038b3-3aa7-4d1f-8a12-1cf0017d5b2c: Heading # Heading
    d6f9a9b8-5dea-469a-af3d-b81ba7040f67: News # News
    d703e6d3-677f-4b60-99d7-44b4710ff7bc: Contact # Contact
    d10684d5-bcd7-4e35-b0be-69377f981c39: Heading # Heading
    dad3b3bd-ab3c-486d-a552-b3cc718f8e1c: Image # Image
    e3b664df-ac52-4b7c-b296-d324800c4b3c: 'Public Schema' # Public Schema
    e6e6fbf0-a370-48de-b635-6f31bece3c9d: 'Slide Layout Centered' # Slide Layout Centered
    e44383bb-8f5a-4b3b-9114-30a955feb64c: Form # Form
    eb7b8bc9-c07a-4a25-9201-8174bd70fcb9: Description # Description
    eb910859-8baf-408a-ae9a-3af97b637806: 'Top Border' # Top Border
    f1b24b40-32c4-47c3-859d-21dd41bbe6f4: Globals # Globals
    f4cfbdf3-fa41-42c6-99f5-d0efefc2e406: 'News Article' # News Article
    f75a20aa-e20c-4f26-b217-2d2ffa1a7cac: 'Stats and Image' # Stats and Image
    f109ee5b-bb41-47ce-aaa0-53b5304e0e22: Heading # Heading
    f466ab59-2e29-4cce-85b8-f9ebe7000b03: 'Internal Link' # Internal Link
    f668aa75-41bb-4309-9114-26d72e1547ff: 'CTA Link' # CTA Link
    fadcfcb9-b6bc-4adf-9adb-18ba2e89bfb7: 'Narrow Width' # Narrow Width
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  default-dashboard:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      excludeAdmin: ''
      logErrors: false
      logInfo: false
      override: ''
      userDashboard: '879'
  freeform:
    edition: lite
    enabled: true
    licenseKey: VKEWWWS910PS87ALDS4HIVX8
    schemaVersion: 4.2.5
    settings:
      ajaxByDefault: '1'
      alertNotificationRecipients: ''
      autoScroll: true
      autoScrollToErrors: ''
      badgeType: ''
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: '1'
      clientDigestRecipients: ''
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: '1'
      defaultView: dashboard
      digestFrequency: '1'
      digestOnlyOnProduction: ''
      digestRecipients: ''
      displayFeed: ''
      emailTemplateDirectory: null
      exportLabels: ''
      fieldDisplayOrder: name
      fillWithGet: '1'
      footerScripts: false
      formFieldShowOnlyAllowedForms: ''
      formSubmitDisable: '1'
      formSubmitExpiration: null
      formTemplateDirectory: ''
      formattingTemplate: flexbox.twig
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: '1'
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: ''
      renderFormHtmlInCpViews: '1'
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: ''
      spamFolderEnabled: false
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: '1'
  guide:
    edition: lite
    enabled: true
    schemaVersion: 2.0.0
    settings:
      assetVolume: a36fa6aa-4824-448f-82cf-b3086f8582c5 # Images
      clientName: 'Europa Museum'
      myCompanyName: 'Pixel & Tonic'
      templatePath: _guide
  imager-x:
    edition: pro
    enabled: true
    licenseKey: 921AV00SG3ZDR1HG4V4K6GSC
    schemaVersion: 3.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: F05LKTHK735ZMFRL0LNY2YWC
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: 'âš™ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: 'ðŸš§âš™ '
      devModeTitlePrefix: 'ðŸš§ '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: false
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: false
      socialMediaPreviewTarget: true
      submitSitemaps: false
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Europa Museum'
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
