fieldLayouts:
  eb1e53f5-82c8-40b9-9072-91da10f51fe7:
    tabs:
      -
        elements:
          -
            fieldUid: 1addbebe-4d59-4c1d-9607-6c47999665df # Links - Middle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 599f0646-f724-4ce4-a810-a8eaf7798b2d # Links - Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Navigation Links'
        sortOrder: 1
handle: navigation
name: Navigation
sortOrder: 1
