defaultPlacement: end
enableVersioning: true
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c42694e0-26f4-46d0-9ffe-3e7fe6a64cb9: # English
    enabledByDefault: true
    hasUrls: true
    template: _/pages/news
    uriFormat: news
type: single
